.circleci/publish-website.sh
build.gradle
gradle.properties
src/guide/xml/guide.xml
src/guide/xml/ref-modes.xml
src/guide/xml/ref-params.xml
src/guide/xml/ref-variables.xml
src/main/xslt/docbook.xsl
src/main/xslt/main.xsl
src/main/xslt/modules/inlines.xsl
src/main/xslt/modules/links.xsl
src/main/xslt/modules/variable.xsl
src/main/xslt/olinkdb.xsl
src/main/xslt/param.xsl
src/main/xslt/xspec-driver.xsl
src/test/resources/expected/olink.001.html
src/test/resources/xml/olink.001.xml
src/test/xspec/link.xspec
src/website/html/homepage.html
src/website/resources/olinkdb/website.olinkdb

The database format isn't backwards compatible with the 1.0 stylesheets, unfortunately.
This PR also prevents publication of the Guide for non-tagged commits.

Initial support for olink

---

.circleci/publish-cdn.sh
src/website/html/homepage.html

Small fixes. I'm not going to bother with a new release for these changes.

Website and CDN fix

---

gradle.properties
src/guide/xml/ch02.xml
src/guide/xml/ch04.xml
src/guide/xml/ch05.xml
src/guide/xml/ref-variables.xml
src/guide/xsl/common.xsl

Drafted something for all the outstanding "fixme:" sections.

Guide updates, bumped version number

---

src/guide/xml/ch05.xml

Just fixed a few incorrect paths.

More doc fixes

---

README.md
src/website/html/homepage.html

Close a couple of minor issues.

Fix a couple of small documentation errors

---

.circleci/config.yml
build.gradle
gradle.properties

The problem was that Gradle was building the URI list during the configuration stage. I don't know why that didn't cause problems on my local environment.

Fix issue #46, make sure catalog.xml isn't empty

---

src/guide/xml/ch05.xml

This is a documentation-only PR

Update build instructions; add prerequisites

---

src/main/xslt/modules/chunk-output.xsl

Correct persistent ToC links across chunks

---

.circleci/publish-cdn.sh

Fix CDN publishing conditional

---

src/bin/docbook.py
src/guide/xml/ch02.xml

This option will copy the system resources (CSS and JS files) from the distribution into the target output directory.

Added --resources option to python script

---

build.gradle
gradle.properties
tools/coverage-report.xsl
tools/report.xsl

1. Fix image links in report and coverage
2. Rework access to Saxon-HE/Saxon-PE based on Saxonica maven repo

Small fixes

---

src/guide/resources/css/guide-toc.css
src/guide/xml/ref-functions.xml

Fix a couple of small issues in formatting for the reference guide.

Guide fixes

---

.circleci/config.yml
build.gradle
buildSrc/build.gradle
gradle.properties
properties.gradle
src/bin/docbook.py
src/test/resources/xspec/xspec.sh
tools/xform-10-tng.xsl

This PR fixes bugs and updates some infrastructure components for the Saxon 10.x (and probably 9.x) versions of the DocBook xslTNG stylesheets.
Internal changes in Saxon 11.x have made it impractical to have a single release for both versions. The `main` branch will go on to be the version for Saxon 11.

The Saxon 10 version of the main branch

---

.circleci/config.yml

This build script will attempt to use JDK8 for release builds.

Fix the JDK version for published builds

---

src/main/xslt/modules/functions.xsl
src/test/resources/xml/orderedlist.004.xml

Gerrit found a better solution (one that works, even)

---

properties.gradle

No longer comes in Saxon 10 and Saxon 11 flavors.

Version 1.7.1 released

---

src/guide/xml/ch02.xml

Fix version numbers in Chapter 2

---

src/website/html/homepage.html

(I edited the `gh-pages` branch by hand, but of course that will get written over next time the website is updated; will the PDF remain, I'm not sure.)

Make sure link to PDF is persistent

---

src/docker/README
src/guide/xml/ch02.xml

Fix some typos and make Docker tag consistent with README and in the guide

Use Docker tag docbook-xsltng consistently

---

src/guide/xml/guide.xml

Added 1.9.0 release notes to the guide

---

.github/workflows/build-pr.yml
build.gradle
tools/homepage.xsl

1. Don't require Pygments to build
2. Fix bug where Pygments was only found in `~/.pyenv`, it should also be found anywhere on the path
3. Don't require a Git clone to build (but the VERSION-ID will be `Unknown`)
4. Attempt to improve the workflows; check PRs, publish to CDN on tagged commit

Tidy up some of the build dependencies

---

.github/workflows/build-branch.yml

Add a GitHub action to publish a release on a tagged commit.

Publish release

---

.github/workflows/build-branch.yml
.github/workflows/build-pr.yml

This PR updates the build automation so that when a release is published, the index files on the CDN are rebuilt.
There are no actual stylesheet changes.

Update CDN indexes after publishing a release

---

properties.gradle
src/guide/xml/guide.xml
src/main/xslt/modules/programming.xsl
src/test/resources/expected/enumsynopsis.001.html
src/test/resources/xml/enumsynopsis.001.xml

Overdue, and convenient excuse to test the new workflows for publishing a tagged release.

Add support for enumsynopsis

---

build.gradle
src/test/xspec/oosynopsis.xspec
tools/report.xsl

This doesn't actually change the output at all.

Fix some errors/problems that had crept into the test report

---

buildSrc/src/main/java/org/docbook/xsltng/extensions/ImageMetadata.java
src/test/resources/xml/fit.001.xml

Extract image metadata from images referenced by data: URIs. Fix the reference to [toc] in _Five Interesting Things_ because I switched to a data: URI image.

Support metadata from data: URIs in images, etc.

---

src/guide/xml/ref-params.xml

Close #211 
I don't know why Tony's PR fails.

Apply PR 211 for @tgraham-antenna

---

src/website/html/homepage.html

This has no effect, and I actually did the tweaks by hand, but this is for next time.

Tweaked homepage

---

.github/workflows/build-branch.yml

This is just tinkering with the build and publication cycle, it makes no changes to the stylesheets.

Save the previous versions of the guide

---

build.gradle
properties.gradle

This PR changes the build process so that the guide is published in versioned directories.

Publish versioned docs

---

.github/workflows/build-pr.yml

There are now stylesheet changes in this PR.

Apply fixes for branches to PR workflow

---

src/main/xslt/modules/variable.xsl

Explicitly convert -output-base-uri to an xs:anyURI

---

build.gradle
src/bin/docbook.py

Fix Python script getting wrong verison of Saxon-HE

---

.github/workflows/build-branch.yml
.github/workflows/build-pr.yml

Do this separately so I can merge it into main before trying to sort out the other PR

Attempt to work around CI failure

---

build.gradle
properties.gradle

The XML Resolver looks for `org/xmlresolver/catalog.xml` so make sure we put one there.

Add catalog.xml to jar file where XML Resolver will find it

---

src/bin/docbook.py

Remove dependency on xml-apis

---

buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestCase.groovy
buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestConfiguration.groovy
properties.gradle
src/guide/xml/ch02.xml
src/guide/xml/changelog.xml
src/guide/xsl/common.xsl
src/main/scss/toc.scss
src/main/web/js/persistent-toc.js
src/website/html/homepage.html

1. Improved the error messages that arise when the persistent ToC is unavailable
2. Improved the documentation for the persistent ToC
3. Cleaned up some dependency checking in the build

Small improvements, hopefully the last 2.x test release

---

src/guide/xml/changelog.xml

Update Guide changelog for 2.1.1

---

build.gradle
buildSrc/src/main/java/org/docbook/xsltng/extensions/ValidateRNG.java
src/test/resources/docbook.rnc

Update the ext:validate-with-relax-ng task to accept RNC grammars

---

properties.gradle
src/guide/xml/ch02.xml
src/main/scss/media-screen.scss

Fix #313 
On Linux, files written to the local filesystem by Docker are owned by root. It's possible to work around this problem, but it isn't pretty.

Document the limitations of Docker on Linux

---

.github/workflows/build-branch.yml
.github/workflows/build-pr.yml

Back out the matrix stuff; it's too broken

---

src/main/scss/media-paged.scss

Attempt to add PDF bookmarks

---

build.gradle
buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestConfiguration.groovy
buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestGenerator.groovy
buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestUtils.groovy

The motivation here was mostly paths with spaces in them. That’s caused a bit of refactoring.

More fixes for Windows builds

---

.github/workflows/build-branch.yml
.github/workflows/build-pr.yml
tools/homepage.xsl

This PR attempts to restore the matrix builds now that they are believed to work on all three platforms.

Fixed matrix builds

---

build.gradle
src/main/scss/README
src/main/scss/media-all.scss
src/main/scss/media-screen.scss
src/main/scss/page-setup.scss

Make new variables; publish SCSS files in distribution

---

build.gradle
src/guide/resources/css/guide-online.css
src/guide/xml/changelog.xml
src/guide/xml/gfdl.xml
src/guide/xml/guide.xml
src/guide/xml/ver2.xml
src/guide/xsl/common.xsl
src/guide/xsl/core.xsl
src/guide/xsl/print.xsl
src/main/xslt/modules/chunk-cleanup.xsl

Moved the changelog off the titlepage and into an appendix. This will make it easier to link to and tidy up the PDF a bit.
Also fixed some bugs in the way chunk navigation was handled in a document with annotations.

Update the way the changelog is managed

---

src/guide/xml/ref-params.xml
src/main/xslt/docbook-paged.xsl
src/main/xslt/modules/objects.xsl
src/main/xslt/modules/tablecals.xsl
src/main/xslt/transforms/20-db4to5.xsl
src/main/xslt/transforms/70-xlinkbase.xsl

Fix errant uses of $debug; document templates-matches

---

src/guide/xsl/common.xsl
src/main/scss/media-paged.scss

Fix problems with Index by Module and running heads in PDF

---

src/guide/xml/ch05.xml

Document gradle.properties

---

src/main/scss/media-paged.scss

Enable hyphenation in paged media

---

src/main/scss/media-paged.scss

Fix #352 
In paged media, the page layout CSS specifies the margins.

Remove body margins in paged-media

---

buildSrc/src/main/java/org/docbook/xsltng/extensions/ImageMetadata.java
buildSrc/src/main/java/org/docbook/xsltng/extensions/ImageProperties.java
buildSrc/src/main/java/org/docbook/xsltng/extensions/ValidateRNG.java

Close #174 
(The XInclude extension doesn't need it either.)

Make sure copyLocalData isn't needed

---

properties.gradle
src/guide/xml/changelog.xml

Bump version, update change log

---

buildSrc/src/main/groovy/org/docbook/xsltng/gradle/ValidationTasks.groovy
src/main/xslt/transforms/20-db4to5.xsl
src/test/resources/expected/db45.001.html
src/test/resources/xml/db45.001.xml

Fix #420 
Oddly, there was no test for that code path.

Missing namespace prefix in 20-db4to5.xsl

---

src/guide/xml/ch04.xml

Correct typo

---

src/guide/xml/ch02.xml

Credit to @fsteimke ; I just tweaked the prose a bit.
Close #457 
Close #452

Describe how to use xslTNG with Oxygen

---

build.gradle
tools/homepage.xsl

This PR fixes a bug where CI builds in repositories where no releases have occurred would fail.

Fix build issues in CI

---

build.gradle
buildSrc/build.gradle
gradle/wrapper/gradle-wrapper.properties
src/guide/xml/changelog.xml
src/main/scss/media-all.scss
src/main/scss/media-screen.scss

I wrote this a while back and it's been sitting on a branch. Let's merge it!

Support "panelset" presentation of variable lists

---

src/main/locale/zh_cn.xml

Add gentext for "danger" to the zh_cn localization

---

src/main/scss/media-screen.scss
src/main/web/js/persistent-toc.js

Make sure the persistent ToC is visible in chunked output

---

src/main/scss/media-screen.scss

Fix #490 
Yes,  moving the footer "up" a bit seems like a reasonable fix. Thanks @jodekirk

Fix bottom-bar navigation

---

.github/workflows/build-branch.yml

I think this will fix the build issue that's plagued the last few releases. The problem is in updating the CDN indexes. This (plus a change in the CDN repository) should fix the problem.

Attempt to fix CI build issue

---

src/main/scss/media-paged.scss

Make PDF output 11pt by default

---

src/main/xslt/modules/xform-locale.xsl

Fix #563 
Thanks @hutchkintoot

Fix typo in stylesheet: lt:page becomes lt:pagenum

---

src/guide/xml/ref-modes.xml
src/guide/xml/ref-params.xml
src/main/scss/media-all.scss
src/main/xslt/modules/unhandled.xsl

Support different options for dealing with unhandled elements

---

src/guide/xml/ch04.xml
src/guide/xml/ref-params.xml
src/main/xslt/modules/templates.xsl

Add parameter for URI of file with default templates

---

src/main/xslt/modules/unhandled.xsl

Bring docs and code into sync for on-unhandled-elements

---

properties.gradle
src/guide/xml/changelog.xml
src/main/xslt/modules/gentext.xsl

Rolling up a bunch of recent changes.

DocBook xslTNG version 2.6.0

---

src/guide/xml/ref-params.xml
src/main/xslt/docbook-paged.xsl
src/main/xslt/modules/chunk-cleanup.xsl

Fix #625.
Thanks @frankarensmeier

Added a user-document-class parameter

---

.github/workflows/build-branch.yml
build.gradle

Change where `publish` puts the output
Attempt to install more recent `dateutils`

Fussing with CI build
