- README.org
- src/website/html/homepage.html
Fix the badge links so they point at the DocBook repo and not my private one.
Added pointer to xsltng.docbook.org to the README.
This will also test pull requests.
> Fix web links

- build.gradle
- gradle.properties
- src/main/samples/README
- src/main/samples/article.xml
1. Make sure that the xslTNG jar is seeded in docbook.py
2. Rework the way the build is constructed so that the zip includes (some of the core) required libraries
> Build fixes

- src/main/web/js/annotations.js
- src/website/resources/samples/fit/js/annotations.js
The `String.prototype.replaceAll` method is not as widely supported as I thought. Mea culpa.
Close #52
> Avoid .replaceAll()

- src/main/xslt/param.xsl
Changed the default chunking rules so that the first section of a chapter, appendix, or other component is included in the chunk with that component. This will improve the presentation of components that have only a short amount of introductory material before the first section (and greatly improve the presentation when there is no introductory material before the first section).
Fix #45.
> Make first sections part of their parent chunk

- .circleci/publish-cdn.sh
Make sure the CDN current directory is the same as the versioned directory
> Fix the release/xsltng/current directory on the CDN

- .circleci/config.yml
- .circleci/publish-cdn.sh
- build.gradle
- gradle.properties
This PR enables snapshot releases to be published. Commits that are merged into `docbook/main` will be pushed to the DocBook CDN in the `release/xsltng/snapshot` directory. To avoid confusion with tagged releases, the version number will always include `-SNAPSHOT`.
> Publish snapshot releases

- src/main/web/css/docbook.css
- src/main/xslt/modules/bibliography.xsl
- src/test/resources/expected/bibliomixed.001.html
- src/test/resources/xml/bibliomixed.001.xml
- src/test/xspec/bibliography.xspec
This PR fixes #76 by adding a template for `releaseinfo` in `m:bibliomixed` mode.
It also fixes a minor CSS problem. In email addresses, which no longer have background color and border as "ordinary" inline code samlpes do, don't output extra padding before and after. (It puts, for example, extra space before a following comma.)
> Fix #76, small cosmetic improvement in CSS

- src/main/web/css/docbook-paged.css
This fixes creating PDFs with Prince. Previously, Prince would complain
about a parsing error and abort.
I have not tested it with Antenna House because I don't have a license for that. It shouldn't break anything since the `@top-*`, `@bottom-*` things are selectors, which shouldn't have colons
> Remove erroneous colons after CSS selectors in docbook-paged.css.

- build.gradle
- src/guide/xml/ref-params.xml
- src/main/xslt/docbook.xsl
- src/main/xslt/param.xsl
If the `generate-html-page` parameter is true (the default), then an entire HTML page is generated for each document. If it's false, then only the rendered elements are returned. This means the result will not have `html`, `head`, or `body` tags.
> Fix #82 by adding a generate-html-page parameter

- src/guide/xml/ch03.xml
- src/guide/xml/examples/issue84.xsl
- src/main/xslt/modules/chunk-output.xsl
This PR adds documentation and an example of how to produce completely different outputs.
It also fixes the bug that prevented this from working for outputs that weren't HTML pages! :-)
> Fix #84 by always outputting non-HTML contents and adding docs

- src/examples/0083-subtitle-in-headline.xsl
- src/examples/0093-id-on-title.xsl
- src/examples/README
These are customization layers and other examples that are useful but not (yet?) integrated into the guide.
> Add directory for examples

- src/guide/xml/ref-params.xml
- src/main/xslt/drivers.xsl
- src/main/xslt/modules/annotations.xsl
- src/main/xslt/modules/chunk-cleanup.xsl
- src/main/xslt/param.xsl
- src/main/xslt/transforms/60-annotations.xsl
- src/test/resources/expected/annotations.005.html
- src/test/resources/xml/annotations.005.xml
- src/test/xspec/annotations.xspec
Fix #113 
The `$annotation-placement` parameter specifies whether annotation marks should appear at the *very* beginning of the element to which they apply (placement = `before`) or at the very end (placement = `after`, the default).
Individual annotations can position themselves at the beginning or the end with a role attribute value of `before` or `after`.
> Adding an annotation-placement parameter

- build.gradle
- properties.gradle
- src/guide/xml/ref-params.xml
- src/main/web/js/persistent-toc.js
- src/main/xslt/transforms/60-annotations.xsl
* Fix a typo
* Fix #118 
* Fix #119 
* Improve the persistent ToC. Browsers don't really afford holding down shift or meta/alt or anything else so make a checkbox for keeping the persistent ToC open; not the most accessible UX, but... Also fixed bugs where the search hit markers would sometimes persist and the link target computation didn't work for same-document links.
> Bug fixes and improvements to the persistent ToC

- properties.gradle
There's a bug in XML Resolver 3.0.1 that causes it to fail for all JDK releases from 9 on. That's been fixed, pushing this release to update the dependency for the convenience of end users.
> Bump XML Resolver version, push new release

- .circleci/config.yml
- properties.gradle
- src/main/web/css/docbook.css
- src/main/xslt/modules/chunk-cleanup.xsl
- src/main/xslt/modules/programming.xsl
- src/test/resources/element-list.xml
- src/test/resources/expected/packagesynopsis.001.html
- src/test/resources/xml/packagesynopsis.001.xml
* Minor CSS and debug message fixes
* Support DocBook 5.2b12; `namespacesynopsis` -> `packagesynopsis`
> DocBook xslTNG version 1.6.0

- .circleci/config.yml
I couldn't sort out how to make openssl continue working. Using the suggested `-pbkdf2` and `-iter` options to encrypt didn't produce a file that I could decrypt. Even on the system that did the encryption. ¯\_(ツ)_/¯
> Give up on openssl, use gnupg

- build.gradle
Having the 'test' task depend on all the formatting tests was clever and all, but it meant any attempt to run a unit test also had to begin by running all of formatting tests. This PR refactors the formatting tests into a different task and makes that a dependency on `requirePassingTests`.
> Refactor test dependencies

- src/main/xslt/modules/verbatim.xsl
- src/test/resources/expected/screen.002.html
- src/test/resources/xml/screen.002.xml
If a continuing verbatim environment was preceded by two or more environments of the same type, the stylesheets would fail.
Fix #156
> Fix verbatim continuations

- .github/workflows/build-branch.yml
- build.gradle
- properties.gradle
1. Fixed `build.gradle` to make a release directory
2. Publish the release on tagged commits
3. Push to CDN on tagged commits
I've now tested this on my own repos and I believe it will all work correctly...
> Prepare to release 1.9.1

- .github/workflows/build-branch.yml
Building `gh-pages` for a release has been deleting previous versions of the EPUB and PDF that were added the branch by hand.
> Attempt to preserve EPUB and PDF

- build.gradle
- properties.gradle
- src/guide/resources/css/guide-online.css
- src/guide/resources/css/guide-toc.css
- src/guide/xml/ref-params.xml
- src/main/locale/en.xml
- src/main/scss/toc.scss
- src/main/web/js/persistent-toc.js
- src/main/xslt/modules/chunk-output.xsl
- src/main/xslt/modules/variable.xsl
- src/test/resources/xml/fit.002.xml
Reworked how the persistent ToC is generated and used. The XSLT is a bit simpler and the JS is improved. It's now possible to store a single copy of the persistent ToC in a separate document.
> Persistent ToC improvements

- .github/workflows/build-branch.yml
If the build is making a prerelease version of the guide, it *doesn't* create the index, but if it's making a "production" release, it does.
> Preserve guide/index.html

- build.gradle
- properties.gradle
- src/main/scss/media-all.scss
- src/main/xslt/modules/inlines.xsl
- src/main/xslt/modules/objects.xsl
- src/main/xslt/modules/titlepage.xsl
1. Use CSS to put a little space between adjacent `keycap` elements in a `keycombo`. Unfortunately, the semantics of the CSS "adjacent sibling" connector are that it ignores text. That means this technique can't be applied more generally to adjacent keycaps.
2. Added a better error message for an empty, `@function`less `keycap`.
3. Handled the case where a `mediaobject` has no usable media. This can happen, for example, if the object contains only inline `textobject`s
4. Process unexpected elements in titlepage templates in the default, `m:docbook`, mode rather than only processing their children.
5. Removed the warning message about unexpected elements in titlepage templates. To restore it, use `templates` in `$debug`.
6. Updated versions and build dependencies.
> A number of small bug fixes and improvements

- build.gradle
- properties.gradle
- src/guide/resources/css/guide-epub.css
- src/guide/xml/changelog.xml
- src/main/xslt/epub.xsl
- src/main/xslt/modules/epub-chunk.xsl
Turns out EPUB 3.3 checks don't like to have the ToC unlinked from the document. Not sure what the right answer is, but in the short term, I've simply linked it back into the beginning of the document.
I also fixed some EPUB CSS, removed a broken slf4j reference from the build script, updated the change log, and rolled the release version back to 2.0.3 because that release was never made.
> Fix EPUB and some odds and ends

- .github/workflows/build-branch.yml
- buildSrc/src/main/java/org/docbook/xsltng/extensions/Cwd.java
- properties.gradle
- src/guide/xml/ref-params.xml
- src/main/xslt/docbook.xsl
- src/main/xslt/modules/chunk-cleanup.xsl
- src/main/xslt/modules/chunk-output.xsl
- src/main/xslt/modules/chunk.xsl
- src/main/xslt/modules/variable.xsl
- src/test/java/org/docbook/xsltng/extensions/TestCwd.java
Fix #241 
Making the `ext:cwd()` function return an absolute URI means we don't have to resolve it against the `static-base-uri()` which is sometimes an `https:` URI. This necessitated reworking some aspects of `$chunk-output-base-uri` and `$vp:chunk-output-base-uri` a bit.
Tidied up some cruft in `chunk-output.xsl`
Publish the Sonatype release from CI so that the `$XSL:VERSION-ID` is correct.
> Fix ext:cwd() so it returns an absolute URI

- properties.gradle
- src/guide/xml/changelog.xml
- src/main/xslt/modules/chunk-cleanup.xsl
As defined, the function requires an `xs:anyURI`, but that's not always convenient so just let them be strings.
> Fix fp:relative-uri

- properties.gradle
- src/guide/xml/changelog.xml
- src/website/html/homepage.html
This pre-release simply updates the dependencies for the XML Resolver and XInclude extension function to 5.0.0 (each, coincidentally). It also updates the change log in the user guide.
> Pre-release version 2.0.9

- src/main/web/js/pagetoc.js
When the window is made narrow enough to cause the on-page ToC to disappear, restore the margins and padding to recenter the body content.
> Tweak the on-page ToC

- build.gradle
- src/main/xslt/transforms/80-oxy-markup.xsl
- src/test/issues/312/v.xml
Using oxy_delete to remove a CALS table entry produces a table with an invalid number of columns. The CALS to HTML transformation is simply unprepared to deal with this. This code inserts a note about removed cells without breaking the table structure.
Fix #312
> Attempt to avoid creating invalid CALS tables

- src/docker/Dockerfile
This PR contains the following changes:
* Add `UBUNTU_VERSION` argument (defaults to `18.04`) to make it easier to use specific Ubuntu versions at build time (use `docker build --build-args UBUNTU_VERSION=...`)
* Replace deprecated `MAINTAINER` key with `LABEL`
> Amend Dockerfile with arguments and metadata

- src/guide/xml/ch02.xml
Per #313, an an explicit pointer to [podman](https://podman.io).
> Added reference to 'podman' as a Docker alternative

- src/main/scss/media-all.scss
There's some CSS trickery here to avoid extra space below a `calloutlist`. It will work when the last element of the last callout description is a `para`:
```
<calloutlist>
...
<callout>
...
<para>...</para>
</callout>
</calloutlist>
```
I expect that (a) `calloutlist`s are fairly rare and (b) when they're used, they almost always contain paragraphs, so...
Close #310
> Attempt to avoid extra space below a callout list

- buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestGenerator.groovy
- src/main/xslt/modules/blocks.xsl
- src/test/resources/xml/para.004.xml
I miscalculated when I was trying to work out the list of block elements that could occur inside a `para`. Fixed now, I think.
Close #319
> Fix list of block elements for $unwrap-paragraphs

- .github/workflows/build-branch.yml
- .github/workflows/build-pr.yml
For some reason, the Mac build can't retrieve `https://api.github.com/repos/docbook/xslTNG/releases` and I can't work out why. So frustrating!
> Skip Mac too

- src/guide/xml/ref-functions.xml
- src/guide/xml/ref-params.xml
- src/main/xslt/modules/functions.xsl
This PR adds a `$translate-suppress-elements` parameter and a `f:translate-attribute` function to support adding `translate="no"` to elements that should not be translated.
(How this is useful in the HTML output is, now that I consider it more carefully, less obvious.)
Fix #335
> Support translate attribute

- .github/workflows/build-branch.yml
- build.gradle
The root cause of #311 is that Oxygen includes Saxon and if the DocBook xslTNG jar file also includes a different *version* of Saxon, bad happens. To avoid this, I'm adding a `docbook-xslTNG-nosaxon-x.y.z.zip` release that doesn't bundle Saxon. That's the version to use if you want to use the stylesheets in Oxygen or some other environment that bundles its own version of Saxon.
Fix #311
> Publish a distribution without Saxon

- buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestConfiguration.groovy
> Make .xspec tasks depend on expected results

- properties.gradle
- src/guide/xml/changelog.xml
- src/guide/xsl/common.xsl
The bug in `$unwrap-paragraphs` seems kind of serious and a few of the other fixes are nice to have.
> DocBook xslTNG version 2.1.4 released

- build.gradle
- buildSrc/src/main/java/org/docbook/xsltng/extensions/Pygmentize.java
- buildSrc/src/main/java/org/docbook/xsltng/extensions/PygmentizeAvailable.java
- buildSrc/src/main/java/org/docbook/xsltng/extensions/PygmentizeCall.java
- buildSrc/src/main/java/org/docbook/xsltng/extensions/PygmentizeDefinition.java
- src/guide/xml/ref-functions.xml
1. Correctly search for `pygmentize.exe` on Windows.
2. Document the `org.docbook.xsltng.extensions.pygmentize` system property
Close #372
> Fix Pygmentize issues on Windows

- src/guide/xsl/common.xsl
- src/main/xslt/modules/variable.xsl
On Windows, there's no defaulting to UTF-8 (*eyeroll*) so Pygments fails on some Unicode characters. This is, I suppose, partly a consequence of getting Pygmentize to run on Windows. Sigh.
> Fix Pygments for the Guide on Windows

- .github/workflows/build-branch.yml
- .github/workflows/build-pr.yml
I am once again removing `windows-2019` from the matrix build. Even though I've specified `'encoding': 'utf-8'` in the Pygmentize options, it's failing on a literal non-breaking space in the input file. Life is too [expletive] short.
> Skip Windows in the matrix build

- README.md
There is a typo in readme file: 'install' is omitted after pip.
> update the README to change pip [packages] to pip install [packages]

- .github/workflows/build-branch.yml
- .github/workflows/build-pr.yml
Building on MacOS was added when I thought I could get building working on all three platforms (Linux, MacOS, Windows). Since Windows is a persistent fail, let's not waste CPU on MacOS which is very unlikely to differ from Linux.
> Don't build on MacOS in CI

- src/guide/xml/ref-params.xml
- src/main/xslt/docbook.xsl
This PR addresses #440 by adding two new parameters `transformed-docbook-input` and `transformed-docbook-output` to capture the pre-processed DocBook input that will be transformed into HTML and the immediate (HTML-ish) results of that transformation (before chunking).
I've adopted @fsteimke 's proposal in #441 slightly. I've only ever wanted these intermediate results for debugging, and I've been satisfied to just tweak the stylesheets when necessary (for example, the block of commented-out code that's been removed in this PR). But making them options seems reasonable and in that case, I can imagine wanting to capture either one, depending on what I'm debugging.
Thank you, Frank!
Close #440 
Close #441
> Add parameters to capture intermediate transformation results

- src/main/xslt/modules/tablecals.xsl
A warning will appear only if the width of a table is greater than the nominal page width, but not if it is equal.
I hope that there are no problems with whitespace which makes comparison difficult. Otherwise give me a hint.
Greetings, Frank
> Issue 411: Do not warn if a table width is exactly nominal page width

- src/guide/xml/ch03b.xml
Informs in the reference manual that you can`t use $v:custom-localizations to create new groups.
Greetings, Frank
> 434 custom localizations

- src/main/web/js/persistent-toc.js
The persistent ToC is augmented with `rel-path` values. If there's a single file, those values may be just ids (`#id`) where the current JavaScript looks for `file#id`. This patch isn't terribly clever, it just looks for `path#id`, `#id`, and `path`, taking the first it finds.
Fix #451
> Try a little harder to scroll the ptoc into view

- src/guide/xml/ch04.xml
In particular, the fact that the `$transform-original` stylesheet is responsible for preserving the base URI of the input document.
Close #427
> Clarify the semantics of transform-original

- build.gradle
- src/guide/resources/css/guide.css
- src/guide/xml/ch02.xml
- src/guide/xml/ch03.xml
- src/main/xslt/docbook-paged.xsl
- src/website/html/homepage.html
1. Make the EPUB link redirect to the most recent version
2. Update the PDF link
3. Various improvements to the PDF rendering, mostly in CSS, but also turn off `titleabbrev-passthrough` for PDF.
> Improve homepage and PDF

- src/bin/docbook.py
Correct docbook (.py) sample installation path. Resolve a possible symbolic link to bin/docbook before returning its absolute path.
> Enable use of a symlink to bin/docbook (.py)

- src/main/xslt/modules/xref.xsl
Simplified (and corrected?) the test whether an entry in the bibliography has an `abbrev` element as it's first element node, that should be used as the entries label. 
See Issue #479
> Changed determination of label for biblioentry / bibliomixed

- src/bin/docbook.py
- src/guide/xml/changelog.xml
- src/main/java/org/docbook/xsltng/Main.java
Fix #504 
This fixes the underlying Java initialization problem (`java -jar ...`) but not the Python problem.
> Rework Java initialization to support the -catalog option

- build.gradle
- buildSrc/src/main/groovy/org/docbook/xsltng/gradle/TestCase.groovy
- gradle.properties
- src/guide/xml/changelog.xml
- src/main/scss/page-setup.scss
- src/main/scss/vendor-weasyprint.scss
Fix #497 
The `vendor-weasyprint.css` stylesheet works around some of the difficulties with weasyprint.
There's also an incomplete fix for #522 in here.
> Extend the recent vendor-css hook to support Weasyprint

- src/guide/xml/ref-functions.xml
No, @cmsmcq, `validate-with-relax-ng()` does not really return the current working directory.
R.I.P., my friend. 😭 😭 😭 
Fix #499
> Fix copy-and-paste error

- src/guide/xml/ch04.xml
> Attempt to clarify transform-before vs transform original

- properties.gradle
- src/guide/xml/changelog.xml
- src/main/scss/media-screen.scss
Fix #543 
I'm not sure this *really* warrants a 2.4.1 release, but I'm annoyed about having broken the persistent ToC again.
> (Re)fix persistent ToC, release 2.4.1

- .github/workflows/build-branch.yml
- .github/workflows/build-pr.yml
This doesn't have any user-visible effect, it just makes GitHub happier.
> Bump versions of GitHub actions

- src/main/xslt/modules/chunk-output.xsl
Adding the persistent ToC to each file, instead of to a single file loaded by JS, required setting the `$persistent-toc-filename` parameter to the empty sequence. That's not obvious (`persistent-toc-filename="?()"` on the command line), so this PR changes the logic so that an empty sequence or an empty string will have the same effect.
Fix #554
> Allow empty-string to disable persistent-toc-filename

- src/guide/xml/ch02.xml
- src/guide/xml/changelog.xml
- src/guide/xml/ref-params.xml
- src/main/xslt/modules/chunk.xsl
> Added use-id-as-filename parameter

- src/bin/docbook.py
> Disclaimer: The proposed modifications do not improve performance or address any issues, but merely make the code more Pythonish and hopefully less prone to errors. The code has been checked to make sure it follows PEP 8 as well as the latest versions of Python 3 and pylint. To preserve the coding style and preferences of the original author, certain pylint warnings and suggestions have been intentionally muted (disabled checks).
* Removed `pass` (introduced by #505) that is no longer needed since #540 solved the original problem.
* Removed unnecessary semicolons (W0301 - unnecessary-semicolon).
* Removed unnecessary C0103 (invalid-name) check already specified at the class level.
* Removed now optional (since version 2.14) pylint check R0201 (no-self-use).
* Disabled W1514 …
> docbook.py: It's not about the performance, it's about the style.

- src/guide/xml/ref-functions.xml
- src/main/xslt/modules/variable.xsl
- src/main/xslt/standalone-functions.xsl
- src/test/xspec/flatten-path.xspec
Fix #579
I wasn’t actually able to reproduce this bug, but the solution seems reasonable, so I implemented it.
> Remove . and .. path segments from $vp:chunk-output-base-uri

- src/guide/xml/ch03b.xml
I think I thought the background would help orient th reader. I’m no longer sure it does.
Thanks @oliviercailloux 
Close #628
> Move localization “background material” to the end of the chapter

- src/main/xslt/modules/index.xsl
The default scope is the nearest ancestor book, or, if there isn’t an ancestor book, the root of the document.
Fix #620
> Fix error in computed scope for generating an index

- .github/workflows/build-branch.yml
The Sonatype folks changed the publishing API and I can’t be bothered to sort this out in CI today. And yes, I’m a little salty about the breaking change.
> Remove sonatype from CI publication
